name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: pytest
