name: SonarQube Analysis (Local via Docker)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run SonarQube Scanner inside Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=library_service_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://host.docker.internal:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait a bit for analysis to be processed
        run: sleep 10

      - name: Get Quality Gate Status
        run: |
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "http://host.docker.internal:9000/api/qualitygates/project_status?projectKey=library_service_key" \
            > result.json

          cat result.json
          STATUS=$(jq -r '.projectStatus.status' result.json)

          echo "Quality Gate Status: $STATUS"

          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi
